Repository intake/intake, pull requests merged in 2019-02, with the labels that each got.

#259 Adding a favicon
  docs/source/_static/images/favicon.ico
Labels: in progress

#258 Updating docs to refer to the status-dashboard
  README.md
  docs/source/plugin-directory.rst
Labels: in progress

#261 Updating travis to run coveralls
  .travis.yml
  README.md
  conda/meta.yaml
Labels: in progress

#263 Plugin missing message
  docs/source/plugin-directory.rst
  docs/source/roadmap.rst
  intake/catalog/local.py
  intake/catalog/tests/test_local.py
  intake/source/cache.py
Labels: in progress

#243 Explicit __init__ signatures for Catalog, RemoteCatalog
  intake/catalog/base.py
  intake/catalog/remote.py
  intake/cli/server/__main__.py
  intake/conftest.py
Labels: needs review

#270 Patch YAML loader only within context
  intake/catalog/exceptions.py
  intake/catalog/local.py
  intake/config.py
  intake/utils.py
Labels: in progress

#264 Make regex field optional
  docs/source/catalog.rst
  intake/catalog/tests/catalog_caching.yml
  intake/catalog/tests/test_caching_integration.py
  intake/source/cache.py
  intake/source/tests/test_cache.py
Labels: needs review

#237 add data-source persistence
  docs/source/api_base.rst
  docs/source/api_user.rst
  docs/source/catalog.rst
  docs/source/examples.rst
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/persisting.rst
  docs/source/plotting.rst
  docs/source/plugin-directory.rst
  intake/__init__.py
  intake/catalog/base.py
  intake/catalog/entry.py
  intake/catalog/local.py
  intake/catalog/tests/test_caching_integration.py
  intake/catalog/tests/test_local.py
  intake/catalog/tests/test_persist.py
  intake/cli/client/subcommands/cache.py
  intake/cli/client/tests/test_cache.py
  intake/config.py
  intake/conftest.py
  intake/container/dataframe.py
  intake/container/ndarray.py
  intake/container/persist.py
  intake/container/tests/__init__.py
  intake/container/tests/test_generics.py
  intake/container/tests/test_persist.py
  intake/gui/widgets.py
  intake/source/__init__.py
  intake/source/base.py
  intake/source/cache.py
  intake/source/decompress.py
  intake/source/tests/data.zarr/.zarray
  intake/source/tests/data.zarr/0
  intake/source/tests/sources.yaml
  intake/source/tests/test_base.py
  intake/source/tests/test_cache.py
  intake/source/tests/test_npy.py
  intake/source/tests/test_text.py
  intake/source/textfiles.py
  intake/source/zarr.py
  intake/util_tests.py
  scripts/ci/install.sh
  scripts/deps.py
  setup.py
  test_requirements.txt
Labels: enhancement, needs review

#276 Fix GUI
  intake/gui/tests/__init__.py
  intake/gui/tests/test_gui.py
  intake/gui/widgets.py
  test_requirements.txt
Labels: in progress

#277 Add DAT cache mechanism
  docs/source/glossary.rst
  intake/catalog/tests/test_local.py
  intake/source/cache.py
  intake/source/tests/cached.yaml
  intake/source/tests/test_cache.py
  intake/source/textfiles.py
  scripts/ci/install.sh
Labels: in progress

#271 Revisit kwargs in open_remote.
  intake/catalog/remote.py
Labels: needs review

#279 Updating references to ContinuumIO -> intake
  README.md
  docs/source/examples.rst
  docs/source/index.rst
  docs/source/overview.rst
  docs/source/plugin-directory.rst
  docs/source/roadmap.rst
  intake/source/tests/test_cache.py
  setup.py
  templates/README.md
Labels: in progress
