Repository intake/intake, pull requests merged in 2019-04, with the labels that each got.

#313 Add use cases "I want..."
  docs/source/index.rst
  docs/source/use_cases.rst
Labels: needs review

#321 More flexibility with dotted nested entry names
  intake/catalog/base.py
  intake/catalog/tests/dot-nest.yaml
  intake/catalog/tests/test_local.py
Labels: in progress

#306 Get catalog names from several inputs
  intake/catalog/base.py
  intake/catalog/default.py
  intake/catalog/local.py
  intake/catalog/tests/catalog.yml
  intake/catalog/tests/catalog1.yml
  intake/catalog/tests/catalog_named.yml
  intake/catalog/tests/test_local.py
  intake/gui/tests/test_gui.py
Labels: ready

#322 revert odd change to required python version
  setup.py
Labels: in progress

#323 Add cat methods
  intake/catalog/base.py
  intake/catalog/entry.py
  intake/catalog/local.py
  intake/catalog/tests/test_local.py
  intake/utils.py
Labels: needs review

#325 Reorganizing GUI
  docs/source/_static/images/gui1.png
  docs/source/_static/images/gui2.png
  docs/source/_static/images/gui3.png
  docs/source/_static/images/gui4.png
  docs/source/_static/images/gui5.png
  docs/source/_static/images/gui6.png
  docs/source/_static/images/gui_add.png
  docs/source/_static/images/gui_add_local.png
  docs/source/_static/images/gui_add_remote.png
  docs/source/_static/images/gui_builtin.png
  docs/source/_static/images/gui_plot.png
  docs/source/_static/images/gui_plot_yaml.png
  docs/source/_static/images/gui_remove.png
  docs/source/_static/images/gui_search.png
  docs/source/_static/images/gui_search_cat.png
  docs/source/_static/images/gui_search_inputs.png
  docs/source/gui.rst
  examples/GUI.ipynb
  intake/catalog/base.py
  intake/catalog/entry.py
  intake/catalog/gui.py
  intake/gui/__init__.py
  intake/gui/base.py
  intake/gui/catalog/__init__.py
  intake/gui/catalog/add.py
  intake/gui/catalog/gui.py
  intake/gui/catalog/search.py
  intake/gui/catalog/select.py
  intake/gui/catalog/tests/__init__.py
  intake/gui/catalog/tests/test_catalog_add.py
  intake/gui/catalog/tests/test_catalog_search.py
  intake/gui/catalog/tests/test_gui.py
  intake/gui/catalog/tests/test_select.py
  intake/gui/conftest.py
  intake/gui/gui.py
  intake/gui/icons/logo.png
  intake/gui/source/__init__.py
  intake/gui/source/defined_plots.py
  intake/gui/source/description.py
  intake/gui/source/gui.py
  intake/gui/source/select.py
  intake/gui/source/tests/__init__.py
  intake/gui/source/tests/test_gui.py
  intake/gui/source/tests/test_source_select.py
  intake/gui/source/tests/test_source_view.py
  intake/gui/source_select.py
  intake/gui/tests/test_gui.py
  intake/gui/tests/test_init_gui.py
Labels: needs review

#329 Improving pretty_describe func
  intake/gui/source/tests/test_source_view.py
  intake/utils.py
Labels: in progress

#331 Don't pop plots from metadata
  docs/source/api_user.rst
  intake/gui/source/description.py
  intake/gui/source/tests/test_source_view.py
Labels: in progress

#330 Simplify describe and describe_open
  docs/environment.yml
  intake/catalog/entry.py
  intake/catalog/local.py
  intake/catalog/remote.py
  intake/catalog/tests/test_local.py
  intake/catalog/tests/test_remote_integration.py
  intake/cli/client/tests/test_local_integration.py
  intake/cli/server/server.py
  intake/cli/server/tests/test_server.py
  intake/gui/source/description.py
  intake/gui/source/tests/test_source_view.py
  requirements.txt
  test_requirements.txt
Labels: in progress
